### PR TITLE
Fix Heroku cannot start server

### LINKED ISSUE #76: Heroku cannot start the server
## Issue
Heroku staging cannot start the server with following error
```
app[web.1]: 2021/02/02 04:29:11 Failed to start the server cannot parse `postgres://:xxxxx@:/`: invalid port (strconv.ParseUint: parsing "": invalid syntax)
```

### PR DESCRIPTION
**Pull request by gutakk**
## What happened
Resolve #76 

## Insight
- Update GetDatabaseURL function to check mode.
- Add `BASIC_AUTHENTICATION_USERNAME` and `BASIC_AUTHENTICATION_PASSWORD` to Heroku env

## Proof Of Work
https://go-google-scraper-staging.herokuapp.com/

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ func main() {
 	db.SetupRedisPool()
 	oauthServerErr := oauth.SetupOAuthServer()
 	if oauthServerErr != nil {
-		log.Fatal(fmt.Sprintf(startServerFailureError, oauthServerErr))
+		log.Fatal(fmt.Sprintf("Failed to start oauth server: %v", oauthServerErr))
```
Comment (olivierobert) [inline main.go]: How about adding another constant to be consistent?

Comment (gutakk) [reply main.go]: Fixed in 3046d67caea8ccc5ddcdcc103ee60462136f5492

**Review by carryall — APPROVED** [review]

**Review by olivierobert — APPROVED** [review]
